backend:
  name: git-gateway
  branch: main 
media_folder: "public/assets/images" 
public_folder: "/assets/images" 
collections:
    - name: "posts" # Used in routes, e.g., /admin/collections/blog
      label: "Snippets" # Used in the UI
      folder: "src/code-snippets" # The path to the folder where the documents are stored
      create: true # Allow users to create new documents in this collection
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
      fields: # The fields for each document, usually in front matter
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Tags", name: "tags", widget: "list", default: "posts" }
        - { label: "CSS", name: "cssCode", widget: "code" }
        - { label: "HTML", name: "htmlCode", widget: "code" }